project:
  type: website
  output-dir: public

website:
  title: "Quantitative Experience Research"
  navbar:
    title: false
    pinned: true
    collapse: false
    left:
      - text: "Quantitative Experience Research"
        menu:
          - text: Book
          - file: book/chapter-1/index.qmd
          - text: Newsletter
          - newsletters.qmd
          - text: Garden
          - garden.qmd
          - text: About
          - about.qmd
          - text: Blog
          - posts.qmd

  sidebar:
    - title: Book
      collapse-level: 1
      contents: book/**

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



